---
name: App-ZofCMS-Plugin-AntiSpamMailTo
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: '"smart" HTML escapes to protect mailto:foo@bar.com links from not-so-smart spam bots'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::Entities: 1.35
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::AntiSpamMailTo:
    file: lib/App/ZofCMS/Plugin/AntiSpamMailTo.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
